### ISSUE TITLE
Fahrzeug öfter defekt, Dieselfahrzeuge.

### ISSUE THREAD

**Issue by SayoFlufftiger** [SayoFlufftiger/FreshV#3]
Fahrzeug öfter defekt, Dieselfahrzeuge.

**Comment by SayoFlufftiger** [comment]
Bis jetzt nicht reproduzierbar

**Comment by Systenadmin** [comment]
> Bis jetzt nicht reproduzierbar

Wahrscheinlich, weil er mit anderen getankt hat ^^
